### ISSUE TITLE
岛民求助

### ISSUE THREAD

**Issue by mefistoduan** [ylc395/new-kukuku#1]
按照readme所述依次npm install 和 webpack后，命令行报错

I:\work\mefisto-new-kukuku-master\new-kukuku-master>node app.js
I:\work\mefisto-new-kukuku-master\new-kukuku-master\lib\ku.js:9
const [httpGet, httpPost] = ['get', 'post'].map(method => promisify(request[method], { multiArgs: true }));
      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (I:\work\mefisto-new-kukuku-master\new-kukuku-master\app.js:3:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

冒昧求教一下，这个应该怎么解决？

**Comment by ylc395** [comment]
使用新版本的Node.js（6.X以上应该就行了）
